### ISSUE TITLE
리팩토링 진행 중

### ISSUE THREAD

**Issue by YongHee-Kim** [devsisters/XLSXasJSON.jl#1]
정해진 룰로만 되던 방식에서
컬럼명에 따라서 
Dict, Array, Array{Dict, 1} 이 유연하게 구성될 수 있도록 작업

1. Dict의 Key는 "."으로 구분, 그러나 Depth는 무제한 늘릴 수 있다.
`d1.d2.d3.d4.d5 .....`

2. `split(colname, ".")으로 잘라서 제일 마지막 요소가 value의 형태를 결정
- 기본은 Any 
- 컬럼명이 `()`, `(Int)`, `(Float)` 으로 끝날 경우 `Array{T, 1}`
- 컬럼명이 bracelet `[]` 으로 감싸져 있을 경우가 Vector{Dict}, 기존의 `d1[1].d2` -> `d1.[1,d2]`로 바뀐다

**Comment by YongHeeK** [comment]
오 좋은생각이네요 빨리 좀 해주세요

**Comment by YongHee-Kim** [comment]
하다보니까... 이렇게 하지말고 JSON 패키지에서 import해서 만드는게 나아 보이네요.

**Comment by YongHeeK** [comment]
어휴... 그냥 내가 다했다 😠

**Comment by YongHeeK** [comment]
도움말이나 좀 써줘
